loadBalancer:
  host: "localhost"
  port: "8080"

backends:
  addresses:
    - "http://localhost:9000"
    - "http://localhost:9001"
    - "http://localhost:9002"

healthChecker:
  interval: 2

rateLimiter:
  capacity: 10
  refill_rate: 1
  refill_interval: 5
  capacity_vip: 20
  refill_rate_vip: 2

workerPool:
  pool_size: 5
  queue_size: 5

redis:
  host: "localhost"
  port: "6379"
  connection_timeout_sec: 5
  max_idle: 10
  idle_timeout_sec: 300