loadBalancer:
  host: "0.0.0.0"
  port: "8080"

backends:
  addresses:
    - "http://backend-1:9000"
    - "http://backend-2:9001"
    - "http://backend-3:9002"

healthChecker:
  interval: 2

rateLimiter:
  capacity: 10
  refill_rate: 1
  refill_interval: 5
  capacity_vip: 20
  refill_rate_vip: 2

workerPool:
  pool_size: 5
  queue_size: 5